local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("cpp", {

  s("binlift", {
    t({
      "struct BinaryLifting {",
      "    int n, LOG;",
      "    vector<vector<int>> up;",
      "    vector<int> depth;",
      "    vector<vector<int>> adj;",
      "",
      "    BinaryLifting(int n) : n(n) {",
      "        LOG = 0;",
      "        while ((1 << LOG) <= n) LOG++;",
      "        up.assign(n, vector<int>(LOG));",
      "        depth.assign(n, 0);",
      "        adj.assign(n, {});",
      "    }",
      "",
      "    void add_edge(int u, int v) {",
      "        adj[u].push_back(v);",
      "        adj[v].push_back(u);",
      "    }",
      "",
      "    void dfs(int v, int p) {",
      "        up[v][0] = p;",
      "        for (int j = 1; j < LOG; j++)",
      "            up[v][j] = up[ up[v][j-1] ][j-1];",
      "",
      "        for (int to : adj[v]) {",
      "            if (to == p) continue;",
      "            depth[to] = depth[v] + 1;",
      "            dfs(to, v);",
      "        }",
      "    }",
      "",
      "    void build(int root = 0) {",
      "        dfs(root, root);",
      "    }",
      "",
      "    int kth_ancestor(int v, int k) {",
      "        for (int j = 0; j < LOG; j++)",
      "            if (k & (1 << j))",
      "                v = up[v][j];",
      "        return v;",
      "    }",
      "",
      "    int lca(int u, int v) {",
      "        if (depth[u] < depth[v]) swap(u, v);",
      "        u = kth_ancestor(u, depth[u] - depth[v]);",
      "        if (u == v) return u;",
      "",
      "        for (int j = LOG - 1; j >= 0; j--) {",
      "            if (up[u][j] != up[v][j]) {",
      "                u = up[u][j];",
      "                v = up[v][j];",
      "            }",
      "        }",
      "        return up[u][0];",
      "    }",
      "",
      "    int dist(int u, int v) {",
      "        int w = lca(u, v);",
      "        return depth[u] + depth[v] - 2 * depth[w];",
      "    }",
      "};",
    }),
  }),
})
