local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

ls.add_snippets("cpp", {

  s("dsu_rb", {
    t({
      "struct RollbackDSU {",
      "    vector<int> parent, sz;",
      "    vector<pair<int,int>> history;",
      "    int components;",
      "",
      "    RollbackDSU(int n) : parent(n), sz(n, 1), components(n) {",
      "        iota(parent.begin(), parent.end(), 0);",
      "    }",
      "",
      "    int find(int x) {",
      "        while (x != parent[x]) x = parent[x];",
      "        return x;",
      "    }",
      "",
      "    bool unite(int a, int b) {",
      "        a = find(a);",
      "        b = find(b);",
      "        if (a == b) {",
      "            history.push_back({-1, -1});",
      "            return false;",
      "        }",
      "",
      "        if (sz[a] < sz[b]) swap(a, b);",
      "        history.push_back({b, sz[a]});",
      "",
      "        parent[b] = a;",
      "        sz[a] += sz[b];",
      "        components--;",
      "        return true;",
      "    }",
      "",
      "    void rollback() {",
      "        auto [b, oldSize] = history.back();",
      "        history.pop_back();",
      "",
      "        if (b == -1) return;",
      "",
      "        int a = parent[b];",
      "        sz[a] = oldSize;",
      "        parent[b] = b;",
      "        components++;",
      "    }",
      "",
      "    int snapshot() {",
      "        return history.size();",
      "    }",
      "",
      "    void rollback_to(int snap) {",
      "        while ((int)history.size() > snap) {",
      "            rollback();",
      "        }",
      "    }",
      "};",
    }),
  }),
})
